### ISSUE TITLE
satellite-reset script should use `hostname -f`

### ISSUE THREAD

**Issue by matt8754** [RedHatSatellite/satellite-support#66]
See https://github.com/RedHatSatellite/satellite-support/blob/master/satellite-reset#L103 , it is loading qpid certs with `hostname`-*.cert. However, in most cases, `hostname` returns short fqdn leading to this error:

Failed: InternalError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/qpid/messaging/driver.py", line 545, in dispatch
    self.connect()
  File "/usr/lib/python2.7/site-packages/qpid/messaging/driver.py", line 572, in connect
    self._transport = trans(self.connection, host, port)
  File "/usr/lib/python2.7/site-packages/qpid/messaging/transports.py", line 120, in __init__
    cert_reqs=validate)
  File "/usr/lib64/python2.7/ssl.py", line 934, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 547, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory

Using `hostname -f` can avoid this happening...

**Comment by wbclark** [comment]
This should be closed since https://github.com/RedHatSatellite/satellite-support/pull/67 , however I don't have the perms on this repo to do it

**Comment by matt8754** [comment]
I'm closing this.
